Feature/cart
wecode-bootcamp-korea/35-1st-LocTea-backend pull request #10
Opened 2022-07-21 07:28 UTC by WorkYong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [X] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

로그인시 장바구니 GET,POST,DELETE,PATCH를 구현해보자
비로그인시 장바구니도 구현해보자

:: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
데코레이터를 통하여 로그인을 확인하고 장바구니에 유저ID 제품ID 와 갯수를 장바구니에 저장할수 있습니다.
IF문을 활용하여 quantity(갯수) 가 0이거나 0보다 작을때는 오류가 나도록 설정하고
갯수가 하나씩 더해지게 만들었습니다.
get_or_create()를 이용해 이미 있는 품목이면 수량만 증가할 수 있도록 했다. 모델링에서 quantity default= 0을줘서 cart의 다른 데이터가 create되면 quantity는 우선 0으로 들어오고 그다음 입력된 수량값으로 업데이트 된다. 만약 이게 안된다면 if문으로 두가지 경우를 만들었어야했다!

장바구니에 GET을 이용하여 정보를 가져옵니다.

USER,_ID, CART_ID, PRODUCT_ID, TITLE, QUANTITY, PRICE, IMAGE 결과값을 표시합니다.
장바구니에 DELETE 기능구현

데코레이터에서 user정보를 가져오고
cart_id에 딕셔너리'id' 키값을 매칭해서 벨류값을 가져옵니다.(request.GET.get 활용)
쿼리가 하나 이상의 객체를 반환할 수 있다면 multipleobjectsreturned 예외처리를 통해 메세지를 남겼습니다.
장바구니 patch 구현

특정 장바구니를 항목을 수정하면 DB에 업데이트 해준다.
quantity 하나면 변경핟기떄매 patch 메소드를 사용 하였다..
로그인 데이터 처리 (예시 - 백엔드)
조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

POST와 GET을 한번 해봐서인가 그래도 이 부분은 구현하기에는 엄청 어렵지는 않았다.
아직 비로그인 기능을 추가하지는 못화였는데 멘토님꼐서 어떤 기능의 API를 만드려면 진행상황을 하나씩 차근차근
점검하며 그 부분이 해결되지 않으면 넘어가지않고 어떻게 그것을 먼저 해결할지를 고민하고 해결하려고 넘어가라고
조언해주셨다. 너무 과대한 생각과 무작정 코딩을 지양해야겠다. HTTPIE로 실험하면서 프론트엔드의 관점에서 조금이나마 철저하게 대비하려고
노력했다. 아직도 수만가지의 에러가 있겠지만 실제 통신을 해봐야할거같다.

:: 기타 질문 및 특이 사항
없음

2022-07-21 08:11 UTC, bigfanoftim requested changes

2022-07-21 08:11 UTC, bigfanoftim commented on cart/views.py
> +            return JsonResponse({'message': 'SUCCESS'}, status=201)
cart가 생성이 되는 경우가 있고 이미 있는 cart를 업데이트 하는 경우가 있는데 그러면 201로 상태코드를 고정하면 안되겠죠?

그 부분을 좀 더 고민하시고 수정해보시면 좋을 것 같아요!

2022-07-21 08:11 UTC, bigfanoftim commented on cart/views.py
> +            return JsonResponse({'message':'USER_CART_NOT_EXIST'}, status=400)
제 생각에는 없는 경우 굳이 예외처리할 필요가 없을 것 같아요. 애초에 없으면 빈 리스트를 반환해줄테니까요!

2022-07-21 08:11 UTC, bigfanoftim commented on cart/views.py
> +            if not Cart.objects.get(id=cart_id, user=user).exist():
get()은 애초에 매칭되지 않으면 에러가 납니다. 따라서 이 조건문은 의미가 없습니다.

2022-07-21 08:11 UTC, bigfanoftim commented on cart/views.py
> +                return JSONDecodeError({'message':'INVALID_CART_ID'}, status=404)
이 조건문도 마찬가지로 필요가 없을 것 같습니다.

2022-07-22 01:50 UTC, WorkYong commented on cart/views.py
> +            return JsonResponse({'message': 'SUCCESS'}, status=201)
get_or_created 를 좀 더 공부해서 보니 created시 불린으로 0,1이 반환되는걸 보고 이용하면 되겠다 생각이 들어서
이렇게 수정하였습니다.

2022-07-22 01:50 UTC, WorkYong commented on cart/views.py
> +            if not Cart.objects.get(id=cart_id, user=user).exist():
get 메소드 공부 좀 더 하겠습니다.

2022-07-22 06:58 UTC, autoboy4commit commented on cart/urls.py
> +from cart.views import CartView
```suggestion
from django.urls import path

from cart.views import CartView
```
모듈 import 컨벤션 수정해주세요~

2022-07-22 06:58 UTC, autoboy4commit commented on cart/views.py
> +            return JsonResponse({'message': 'SUCCESS'}, status=201)
status code 204는 No Content 아닌가요? 'UPDATE' 라는 message를 return 하는 상황에서 적합하지 않겠죠?

그리고 충분히 찾아보셔서 이미 너무나 잘 아시겠지만 django의 orm중 하나인 `get_or_create` method는 이로 인해 인스턴스가 **'생성'**되었다면 True를, 새로이 생성되지 않은거라면 False를 반환합니다.

따라서 다음과 같이 수정하면 적절할 것 같습니다.

```python
if is_created:
    return JsonResponse({'message' : 'CREATE_SUCCESS'}, status=201)

return JsonResponse({'message' : 'UPDATE_SUCCESS'}, status=200)
```

2022-07-22 06:58 UTC, autoboy4commit commented on cart/views.py
> +
```suggestion

```
가독성을 위해 띄워준거라면 한줄만 띄워도 충분할 것 같습니다.
python은 interpreter 언어로 모든 line을 한줄 한줄 읽으며 실행하기 때문입니다.

2022-07-25 02:51 UTC, bigfanoftim requested changes

2022-07-25 02:51 UTC, bigfanoftim commented on cart/views.py
> +            if is_created == 0 :
is_created가 boolean값으로 나올테니 `if not is_created:` 으로 처리하는 것이 더 좋지 않을까요?

2022-07-25 02:51 UTC, bigfanoftim commented on cart/views.py
> +        carts = Cart.objects.filter(user_id=user)
```suggestion
        carts = Cart.objects.filter(user=request.user)
```
user면 user, id면 id 명확하게 사용해야 합니다. user라는 변수에 request.user의 id를 저장하고
이후에 user_id=user 라는 코드를 보면 오해가 있을 수 있습니다. 파이썬은 타입을 강제할 수 없기 때문에 더욱 네이밍에 신경써야 합니다.
또한 현재 코드에서 굳이 변수에 지정해서 활용할 이유가 없어보입니다.

2022-07-25 02:51 UTC, bigfanoftim commented on cart/views.py
> +            user     = request.user.id
여기도 마찬가지입니다.

2022-07-26 02:46 UTC, bigfanoftim approved these changes
LGTM 👍

2022-07-26 02:46 UTC, merged