[박정용] Orders 기능 구현
wecode-bootcamp-korea/35-1st-LocTea-backend pull request #21
Opened 2022-07-27 07:41 UTC by WorkYong

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
주문페이지를 구현하여 주문명세서 및 배송지를 입력 할 수 있게 만들고 데이터베이스에 저장된다.
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
-  POST 기능을 구현하여 프론트로부터 주문페이지에 내용을 받아 데이터베이스에 저장 합니다.
-  Delivery 테이블을 따로 모델링하여 받는 사람 및 보내는 사람을 따로 작성 할 수 있습니다.
-  프론트에게 GET 메소드를 사용하여 필요한 정보를 전달합니다.
-  주문을 하게되면 장바구니 데이터가 삭제 될 수 있게 구현하였습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- trasaction.atomic()을 사용하여 데이터를 생성하다가 만약 실수를 하게되면 데이터베이스를 자동으로 리붓하는 내부 함수를 알게되었습니다.
- POST,GET 함수를 복습하게 되었습니다.
- 장바구니 데이터가(CART_ID) 어떻게 하면 삭제 되게 될까 고민하고 멘토님의 도움으로 알게 되었습니다.
- 모델링을 한번 더 고민하고 일대 다 관계로 생성하였습니다.

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2022-07-27 08:39 UTC, bigfanoftim requested changes

2022-07-27 08:39 UTC, bigfanoftim commented on core/enums.py
> +    Canceled=2
Enum은 만들어놓고 왜 사용하지 않는걸까요~?
그리고 상수는 전부 대문자로 작성하는 것이 기본 컨벤션입니다.

2022-07-27 08:39 UTC, bigfanoftim commented on orders/views.py
> +    def post(self, request):
오로지 1개의 장바구니만 주문할 수 있는 상황인건가요??

2022-07-27 08:39 UTC, bigfanoftim commented on orders/views.py
> +        } for cart in carts]
order인데 왜 장바구니를 가져오는걸까요?

2022-07-27 13:47 UTC, WorkYong commented on orders/views.py
> +        } for cart in carts]
주문페이지에 장바구니에 담겼던 목록이 필요해서입니다

2022-07-27 13:47 UTC, WorkYong commented on orders/views.py
> +    def post(self, request):
무슨말인지 잘 모르겠어서 질문하겠습니다

2022-07-28 05:16 UTC, bigfanoftim commented on orders/views.py
> +        } for cart in carts]
장바구니에 담긴 목록을 받아오는 view는 이미 cart.views에 작성이 된 것 아니었나요?

2022-07-28 08:26 UTC, bigfanoftim approved these changes

2022-07-28 08:26 UTC, merged